ethereum_onchain_analytics:
  outputs:
    ci:
      account: XZEPDMD-BR83796
      database: CI
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: ACCOUNTADMIN
      schema: ci_eth
      threads: 4
      type: snowflake
      user: celiajb
      warehouse: COMPUTE_WH
  target: ci