ethereum_onchain_analytics:
  outputs:
    ci:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: CI
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: ci_eth
      threads: 4
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
  target: ci