config-version: 2

name: 'ethereum_onchain_analytics'
version: '1.0.0'

profile: 'ethereum_onchain_analytics'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

flags:
  fail_fast: true

seeds:
  +schema: seeds

models:
  ethereum_onchain_analytics:
    staging:
      +schema: eth_bronze
      +materialized: view
    intermediate:
      +schema: eth_silver
      +materialized: table
    marts:
      +schema: eth_gold
      +materialized: table
      +tags: ['analytics']

      analytics:
        stablecoin_activity_per_day:
          +post-hook: 
            - GRANT USAGE ON DATABASE {{ target.database }} TO ROLE DA
            - GRANT USAGE ON SCHEMA {{ target.database }}.{{ this.schema }} TO ROLE DA
            - GRANT SELECT ON {{ this }} TO ROLE DA